export class MyExpensesPage {

    details = {
        zeplin : () => 'https://zpl.io/Q0pgyo4',
        overflow : () => 'https://overflow.io/s/24CP2JIV/?node=18740a43',
    }
 
     elements = {
        // MY EXPENSES SECTION
        lblMyExpenses: () => cy.get('[]'),
        btnSync: () => cy.get('[]'),
        rbMonthAndYear: () => cy.get('[]'),
        iconTotalSpent: () => cy.get('[]'),
        lblTotalSpent: () => cy.get('[]'),
        iconTotalSpentRupee: () => cy.get('[]'),
        valTotalSpent: () => cy.get('[]'),
        iconIncome: () => cy.get('[]'),
        lblIncome: () => cy.get('[]'),
        iconIncomeRupee: () => cy.get('[]'),
        valIncome: () => cy.get('[]'),
        imgSpentAndIncomeGraph: () => cy.get('[]'),
        // RECENT TRANSACTIONS SECTION
        lblRecentTransactions: () => cy.get('[]'),
        lblViewAll: () => cy.get('[]'),
        lnkRecentTransactionsViewAll: () => cy.get('[]'),
        iconTransactions: () => cy.get('[]'),
        lblTransactions: () => cy.get('[]'),
        subTxtTransactionsMode: () => cy.get('[]'),
        iconTransactionsSpentandIncome: () => cy.get('[]'),
        lblTransactionsSpentandIncomeDate: () => cy.get('[]'),
        valTransactionsSpentandIncome: () => cy.get('[]'),
        // MY ACCOUNTS SECTION
        lblMyAccounts: () => cy.get('[]'),
        iconBankAccounts: () => cy.get('[]'),
        lblBankAccounts: () => cy.get('[]'),
        valBankAccounts: () => cy.get('[]'),
        lnkBankAccountsViewAll: () => cy.get('[]'),
        lblBankName: () => cy.get('[]'),
        lblBankBalance: () => cy.get('[]'),
        subTxtBankAccountLastUpdatedOn: () => cy.get('[]'),
        iconCreditCards: () => cy.get('[]'),
        lblCreditCards: () => cy.get('[]'),
        valCreditCards: () => cy.get('[]'),
        lnkCreditCardsViewAll: () => cy.get('[]'),
        lblCreditCardsBankName: () => cy.get('[]'),
        valMaskedCreditCardNumber: () => cy.get('[]'),
        txtCreditCardDueDate:() => cy.get('[]'),
        dateCreditCardDueDate:() => cy.get('[]'),
        lblCreditCardBalance: () => cy.get('[]'),
        valCreditCardBalance: () => cy.get('[]'),
        subTxtCreditCardLastUpdatedOn: () => cy.get('[]'),
        iconLoanAccounts: () => cy.get('[]'),
        lblLoanAccounts: () => cy.get('[]'),
        valLoanAccounts: () => cy.get('[]'),
        lnkLoanAccountsViewAll: () => cy.get('[]'),
        lblLoanAccountsBankName: () => cy.get('[]'),
        valMaskedLoanAccountsNumber: () => cy.get('[]'),
        lblAccountsDueDate:() => cy.get('[]'),
        dateLoanAccountsDueDate:() => cy.get('[]'),
        lblLoanAccountsEmiDueDate: () => cy.get('[]'),
        valLoanAccountsEmiDue: () => cy.get('[]'),
        subTxtLoanAccountsLastUpdatedOn: () => cy.get('[]'),
        iconInvestment: () => cy.get('[]'),
        lblInvestment: () => cy.get('[]'),
        valInvestment: () => cy.get('[]'),
        lnkInvestmentViewAll: () => cy.get('[]'),
        lblInvestmentBankName: () => cy.get('[]'),
        lblInvestmentBalance: () => cy.get('[]'),
        valInvestmentBalance: () => cy.get('[]'),
        subTxtInvestmentLastUpdatedOn: () => cy.get('[]'),
        iconWallets: () => cy.get('[]'),
        lblWallets: () => cy.get('[]'),
        valWallets: () => cy.get('[]'),
        lnkWalletsViewAll: () => cy.get('[]'),
        lblWalletsBankName: () => cy.get('[]'),
        lblWalletsBalance: () => cy.get('[]'),
        valWalletsBalance: () => cy.get('[]'),
        lblWalletsLastUpdatedOn: () => cy.get('[]'),
        iconFAQ: () => cy.get('[]'),
        lblFAQ: () => cy.get('[]'),
        lnkFAQ: () => cy.get('[]'),      
     }
  }
 
 export const myExpensesPage = new MyExpensesPage
