
// import { homePage } from "../../pages/home/HomePage"
// import { fplPage } from "../../pages/loan/fpl/FPLPage"
// import { fplLoanAmountDetailsPage } from "../../pages/loan/fpl/FPLLoanAmountDetailsPage"
// import { fplLoanAmountTenurePage } from "../../pages/loan/fpl/FPLLoanAmountTenurePage"
// import { applyCouponCodeOrPointsPage } from "../../pages/generic/ApplyCouponCodeOrPointsPage"
// import { repaymentSchedulePage } from "../../pages/loan/RepaymentSchedulePage"
// import { loanPurposePage } from "../../pages/loan/LoanPurposePage"
// import { selectBankAccountPage } from "../../pages/bank/SelectBankAccountPage"
// import { signLoanDocumentPage } from "../../pages/loan/SignLoanDocumentPage"
// import { kfsSanctionLetterPage } from "../../pages/loan/KFSSanctionLetterPage"
// import { signDocumentPage } from "../../pages/loan/SignDocumentPage"
// import { signServicePage } from "../../pages/loan/SignServicePage"
// import { signServiceOTPInputPage } from "../../pages/loan/SignServiceOTPInputPage"
// import { loanApplicationSubmittedPage } from "../../pages/loan/sa/LoanApplicationSubmittedPage"

// // SA loan
// import { saLoanAmountTenurePage } from "../../pages/loan/sa/SALoanAmountTenurePage"
// import { saLoanAmountDetailsPage } from "../../pages/loan/sa/SALoanAmountDetailsPage"

// //insurance 

// import { footerPage } from "../../pages/generic/FooterPage"
// import { accountsPage } from "../../pages/accounts/AccountsPage"


// //Profile status
// import { profileInformationPage } from "../../pages/onboarding/profile/ProfileInformationPage"


// import { csrInfoPage } from "../../pages/creditScoreReport/CSRInfoPage"
// import { csrProfileInformationPage } from "../../pages/creditScoreReport/CSRProfileInformationPage"
// import { csrOTPInputPage } from "../../pages/creditScoreReport/CSROTPInputPage"
// import { csrPaymentOptionsPage } from "../../pages/creditScoreReport/CSRPaymentOptionsPage"

// import { forecloseLoanPage } from "../../pages/repayments/ForecloseLoanPage";
// import { foreclosureReasonPage } from "../../pages/repayments/ForeclosureReasonPage"
// import { emailAddressInputPage } from "../../pages/onboarding/profile/generalInformation/EmailAddressInputPage"
// import { saProductDetailsPage } from "../../pages/loan/sa/SAProductDetailsPage"
// import { saEmpDetailsPage } from "../../pages/loan/sa/SAEmpDetailsPage"
// import { saVerifyEmploymentPage } from "../../pages/loan/sa/SA-VerifyEmploymentPage"
// import { paymentOptionPage } from "../../pages/payments/PaymentOptionPage"
// import { verifyWorkEmailInfoPage } from "../../pages/pd/basicDetails/verifyWorkEmail/VerifyWorkEmailInfoPage"
// import { verifyWorkEmailPage } from "../../pages/pd/basicDetails/verifyWorkEmail/verifyWorkEmailPage"
// import { verifyWorkEmailOTPInputPage } from "../../pages/pd/basicDetails/verifyWorkEmail/VerifyWorkEmailOTPInputPage"
// import { saVerifyWorkEmailRefreshPage } from "../../pages/loan/sa/SAVerifyWorkEmailRefreshPage"

// describe('Account , Settings , Loan , SA', () => {
//     it('Login With Mobile Number', () => {

//         const DBurl = "https://gt1vbgrgml.execute-api.ap-south-1.amazonaws.com/Automation/qsometest";
//         const mobilenum = "6302886939"
//         const dbip = "10.105.60.156"
//         cy.visit('/login', { failOnStatusCode: false });
//         cy.log('navigated to login page');
//         cy.contains('span','Login/Signup with Mobile').click({ force: true });
//         cy.url().should('include', '/loginwithmob/mobileform');
//         cy.get('input')
//             .should('be.visible')
//             .and('have.attr', 'placeholder', '10 digit mobile number')
//             .and('have.attr', 'maxlength', '10')
//             .next()
//             .prev()
//             .type(mobilenum);
//         cy.get('[data-cy="checkboxText"]').click()
//         cy.wait(1000);
//         cy.get('[data-cy="app.components.Common.continue_btn_caps"]')
//             .click();
//         cy.wait(4000);
//         cy.url().should('include', '/loginwithmob/otpvalidation');

//         cy.log("DBurl :" + DBurl);
//         cy.log("mobilenum :" + mobilenum);
//         cy.log("dbip :" + dbip);

//         //SELECT otp from yp_user_otp  WHERE sentTo =6302886939  order by id desc limit 10
//         var payload = { "query": "SELECT otp from `yp_user_otp` WHERE `sentTo` ='6302886939' order by id desc limit 1", "db_ip": "10.105.60.156" };
//         cy.log(payload)
//         cy.wait(3000)
//         cy.request('POST', 'https://gt1vbgrgml.execute-api.ap-south-1.amazonaws.com/Automation/qsometest', payload).then((resp) => {
//             cy.wait(4000)
//             cy.log(resp.status)
//             cy.log(resp.body['body'])
//             cy.wait(1000)
//             const sixdigitotp = resp.body['body'];
//             var rx = "\\d{6}"
//             var otp = parseInt(sixdigitotp.match(rx))
//             cy.log("OTP :" + otp)
//             cy.get('input')
//                 .should('be.enabled')
//                 .and('have.attr', 'placeholder', 'Enter OTP Here')
//                 .click()
//                 .type(otp);
//         })
//         cy.wait(2000);
//     })
// it('KB-T54079 (1.0)Ensure for cash loan source loanSignService Consent should be store in yp_user_consent table whenever user is doing esign during loan creation along with tncid,Policyid, Usercashlimit,Consnetid , ConsentBody ,Version and appytpe .', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-MLASILVER.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: 'loan/fpl/fplPage-5k.json' })
//     cy.intercept('**/preloanre?productId=14&action=getNow&preLoanEvent=preLoanGetNowClick&src=cash', { fixture: 'loan/fpl/fplLoanAmountTenurePage-preLoanRE-srcCash.json' })
//     cy.intercept('**/products?productId=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-productID14.json' })
//     cy.intercept('**/products/calcfees?productid=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-feescalculations.json' })
//     cy.intercept('**/me/bank?productid=**', { fixture: 'bank/bankAccountVerifiedPage.json' })
//     cy.intercept('**/loan/la?updateMFILimit=**', { fixture: 'loan/signLoanDocumentPage-Enable-ESignAndDigFaceID.json' })
//     cy.intercept('**/loan/la?type=**', { fixture: 'loan/fpl/sanctionPage-fund-WC.json' })
//     cy.intercept('**/me/otp?reason=clickwrap&kbloanId=**', { fixture: 'otp/otp-sanctionOTP.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFPL4KGetNowBtn()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.verifyTotalIntrestLabel('Total Interest')
//     fplLoanAmountDetailsPage.verifyFeeAndchargesLabel('Fees & Charges')
//     fplLoanAmountDetailsPage.verifyGSTlbl('GST @ 18%')
//     fplLoanAmountDetailsPage.verifyTenureLabel('TENURE')
//     fplLoanAmountDetailsPage.verifyTransferToBankLabel('TRANSFER TO BANK')
//     fplLoanAmountDetailsPage.verifyBuyEMIText('Buy EMI Protect : ₹ 73')
//     fplLoanAmountDetailsPage.verifyApplyCouponCodeLabel_1('Apply Coupon code or Points')
//     fplLoanAmountDetailsPage.verifyRepaymentShedulePageButton()
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.verifyPrincipalLabel('Principal')
//     repaymentSchedulePage.verifyInterestLabel('Interest')
//     repaymentSchedulePage.verifyDueDateLabel('Due Date')
//     repaymentSchedulePage.verifyRepayableAmountLabel('Repayable Amount')
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.clickDigitalSignButton()
//     signLoanDocumentPage.clickContinueBtn()
//     //kfs sanction letter - validation
//     kfsSanctionLetterPage.verifyPageTitle('Sanction letter')
//     kfsSanctionLetterPage.verifyLoanSanctionedByLabel('Your loan is being sanctioned by:')
//     kfsSanctionLetterPage.verifyLenderNameText('Western Capital Advisors Private Limited & Krazybee Services Private Limited.')
//     kfsSanctionLetterPage.verifyContinueToSignLoanDocumentText('Continue to Sign Loan Document')
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     //sanction letter -validation
//     signDocumentPage.verifyPageTitle('Sign Document')
//     signDocumentPage.verifyInfoSignDocumentText('These Standard Terms & Conditions along with the Most Important Terms and Conditions form a legal and binding agreement upon acceptance pursuant to the Indian Contract Act, 1872 and the Information Technology Act, 2000.')
//     signDocumentPage.verifyContinueText('Continue')
//     signDocumentPage.clickContinueButton()
//     //signServicePage - validation
//     signServicePage.verifyPageTitle('Sign Service')
//     signServicePage.verifyTransactionIDLabel('Transaction ID:')
//     signServicePage.verifyTransactionIDValue('KBDID20221125cR9ofKxteb811837')
//     signServicePage.verifyDateAndTimeLabel('Date & Time:')
//     signServicePage.verifyDeviceIDLabel('Device ID:')
//     signServicePage.verifyDeviceIDValue('')
//     signServicePage.verifyIPAddressLabel('IP Address:')
//     signServicePage.verifyIPAddressValue('122.185.107.110')
//     signServicePage.verifyConsentReadText('I had carefully read the Standard Terms and Conditions and the Most important Terms and Conditions for availing loan from the lender')
//     signServicePage.verifyConsentUnderstoodText(' I had understood and read the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender.')
//     signServicePage.verifyConsentLegalAndBindingText(' I had further understand that upon acceptance of the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender, a legal and binding agreement shall be created between us under the Indian Contract Act, 1872 read with Information Technology Act, 2000.')
//     signServicePage.selectConsent()
//     signServicePage.verifyContinueButtonText('Continue ')
//     signServicePage.clickContinueButton()
//     // //OTP service validation
//     cy.clock()
//     signServiceOTPInputPage.enterOTP('123456')
//     // cy.tick(4000)
//     //signServiceOTPInputPage.verifyTimerValue('(00:26)')
// })

// it('KB-T52699 (1.0) Ensure SA Loan Creation is success when both PD Points and Coupon is applied', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-MLASILVER.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: 'loan/fpl/fplPage-5k.json' })
//     cy.intercept('**/preloanre?productId=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-preLoanRE-srcCash.json' })
//     cy.intercept('**/products?productId=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-productID14.json' })
//     cy.intercept('**/products/calcfees?productid=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-feescalculations.json' })
//     cy.intercept('**/products/verifycoupon?productid=**', { fixture: 'loan/repaymentSchedulePage/verifyCouponcode.json' })
//     cy.intercept('**/me/bank?couponCode=**', { fixture: 'bank/bankAccountVerificationPage-CouponCode.json' })
//     cy.intercept('**/loan/la?updateMFILimit=**', { fixture: 'loan/signLoanDocumentPage-Enable-ESignAndDigFaceID.json' })
//     cy.intercept('**/loan/la?type=**', { fixture: 'loan/fpl/sanctionPage-fund-KreditBeePVTLTD.json' })
//     cy.intercept('**/me/tnc/loanSanctionLetter', { fixture: 'loan/loanSanctionLetterPage.json' })
//     cy.intercept('**/me/otp?reason=clickwrap&kbloanId=**', { fixture: 'otp/otp-sanctionOTP.json' })

//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFPL4KGetNowBtn()
//     fplLoanAmountTenurePage.scrollSliderselectLoanAmount()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.clickApplyCouponCodeLabel()
//     applyCouponCodeOrPointsPage.enterCouponCodeInput('TEST11')
//     applyCouponCodeOrPointsPage.verifyPageTitle('Apply Coupon code or Points')
//     applyCouponCodeOrPointsPage.clickApplyBtn()
//     // fplLoanAmountDetailsPage.verifyCouponAppliedLabel('Apply Coupon code ')
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.clickDigitalSignButton()
//     signLoanDocumentPage.clickContinueBtn()
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     signDocumentPage.verifyContinueText('Continue')
//     signDocumentPage.clickContinueButton()
//     signServicePage.verifyIPAddressValue('122.185.107.110')
//     signServicePage.verifyConsentReadText('I had carefully read the Standard Terms and Conditions and the Most important Terms and Conditions for availing loan from the lender')
//     signServicePage.verifyConsentUnderstoodText(' I had understood and read the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender.')
//     signServicePage.verifyConsentLegalAndBindingText(' I had further understand that upon acceptance of the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender, a legal and binding agreement shall be created between us under the Indian Contract Act, 1872 read with Information Technology Act, 2000.')
//     signServicePage.selectConsent()
//     signServicePage.verifyContinueButtonText('Continue ')
//     signServicePage.clickContinueButton()
//     cy.clock()
//     signServiceOTPInputPage.enterOTP('123456')
//     cy.tick(4000)
//     signServiceOTPInputPage.verifyTimerValue('(00:26)')
// })

// it('KB-T4838 (1.0) Check whether SA banner with Apply Now is displayed in My Accounts', () => {
//     cy.intercept('**/home', { fixture: '/home/homePage-SA-Accounts-Open.json' })
//     cy.intercept('**/myaccount', { fixture: '/accounts/accoutPage-SA-Enabled.json' })

//     cy.visit('/newhome', { failOnStatusCode: false });
//     footerPage.clickAccountIcon()
//     accountsPage.verifySALoanLabel('Salaried Loan')
//     accountsPage.verifySALoanSubText('Complete your Salary profile to avail higher amount')
//     accountsPage.verifySAApplyNowButton('Apply Now')

// })

// it('1-KB-T59856 (1.0)[Business Case] Verify cooloff option is shown based on the monthlyCooloffCount config set', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-MLAX-disbursal.json' })
//     cy.intercept('**/me/loans', { fixture: 'repayments/repaymentPage-loanMLAX.json' })
//     cy.intercept('**/pg/me/payment?v=sp3&reqId=30105322&type=foreclosure', { fixture: 'payments/paymentOptionPage.json' })
//     cy.intercept('**/me/loan?id=KBST221215ITJ', { fixture: 'repayments/repaymentPage-loanID-MLAX.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickPayNowButton()
//     repaymentPage.verifyForecloseTitle('Foreclose Loan')
//     repaymentPage.verifyForecloseTitle('Foreclose Loan')
// })

// it('2-KB-T59856 (1.0)[Business Case] Verify cooloff option is shown based on the monthlyCooloffCount config set', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-MLAX-disbursal.json' })
//     cy.intercept('**/me/loans', { fixture: 'repayments/repaymentPage-loanMLAX.json' })
//     cy.intercept('**/me/loan?id=**', { fixture: 'repayments/repaymentPage-loanID-MLAX.json' })
//     cy.intercept('**/pg/me/payment?v=sp3&reqId=30105322&type=foreclosure', { fixture: 'payments/paymentOptionPage.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickPayNowButton()
//     repaymentPage.verifyForecloseTitle('Foreclose Loan')
//     repaymentPage.verifyForecloseTitle('Foreclose Loan')
//     repaymentPage.clickForeclosePaynow()
//     forecloseLoanPage.verifyForeCloseloanLabel('Foreclose Loan')
//     // forecloseLoanPage.clickPayLoanAmountBtn()
// })

// it('3-KB-T59856 (1.0)[Business Case] Verify cooloff option is shown based on the monthlyCooloffCount config set', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-MLAX-disbursal.json' })
//     cy.intercept('**/me/loans', { fixture: 'repayments/repaymentPage-loanMLAX.json' })
//     cy.intercept('**/me/loan?id=KBST221215ITJ', { fixture: 'repayments/repaymentPAge-loanID-MLAX-Foreclosure-Amount1500.json' })
//     cy.intercept('**/loan/foreclosure/event', { fixture: 'repayments/repaymentPage-event.json' })
//     cy.intercept('**/loan/foreclosure/reasons', { fixture: 'repayments/repaymentPage-ForeclosureReasons.json' })
//     cy.intercept('**/pg/me/payment?v=**', { fixture: 'payments/paymentOptionPage.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickPayNowButton()
//     repaymentPage.clickForeclosePaynow()
//     forecloseLoanPage.clickPayLoanAmountBtn()
//     foreclosureReasonPage.selectForecloseReason('I do not need the loan now')
//     foreclosureReasonPage.clickContinueBtn()
//     paymentOptionPage.clickDebitCardBlock()
// })

// it('KB-T3725 (1.0)Check that for cash loan if any of the Onboarding Fees/Reassessment Fees/Doc Collect Fees is enabled for the user should be deducted in amount disbursed', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-6.2kFPL.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: 'loan/fpl/fplPage-6.2k.json' })
//     cy.intercept('**/preloanre?productId=14&action=getNow&prIeLoanEvent=preLoanGetNowClick&src=cash', { fixture: 'loan/fpl/fpl6.2KPreloanREPage.json' })
//     cy.intercept('**/products?productId=**', { fixture: '/loan/fpl/viewSummayAndChargesPage.json' })
//     cy.intercept('**/products/calcfees?productid=14&loanamt=6200&tenure=**', { fixture: 'loan/fpl/fplLoanAmountDetailsPage-FeesCalculation.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFPL4KGetNowBtn()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.verifyFeeAndchargesLabel('Fees & Charges')
//     fplLoanAmountDetailsPage.verifyProcessingFee('Processing Fee')
//     fplLoanAmountDetailsPage.verifyOnboardingFeeLabel('One Time Onboarding Fee')
//     fplLoanAmountDetailsPage.verifyCSRFeeLabel('Credit Score Report Fee')
//     fplLoanAmountDetailsPage.verifyGSTlbl('GST @ 18%')
//     fplLoanAmountDetailsPage.verifyLoanDocumantSigningFee('Loan Document Fee')
//     fplLoanAmountDetailsPage.verifyTransferToBankLabel('TRANSFER TO BANK')
// })

// it('KB-T21311 (1.0)Check the soft back and hard back buttons on Work Email Validation info screen after Extra Details page in profile flow', () => {
//     cy.intercept('**/home', { fixture: '/home/homePage-HomePage-ContinueApplication.json' })
//     cy.intercept('**/me', { fixture: 'onBoarding/profile/profileInformation-KYCCompleted.json' })
//     cy.intercept('**/me/substateinfo', { fixture: 'onBoarding/profile/profileinfo-Sub-General.json' })
//     cy.intercept('**/email?reason=verificationStatus', { fixture: 'onBoarding/profile/EmailAdressPage.entering.json' })
//     cy.intercept('**/otp?reason=emailRegister&email=**', { fixture: 'onBoarding/profile/verifyEmailOtp-Submitted.json' })
//     cy.intercept('**/me?type=thumbnail', { fixture: 'onBoarding/profile/KycDocSubmited.json' })

//     cy.visit('/newhome ', { failOnStatusCode: false })
//     homePage.clickContinueApplicationBtn()
//     profileInformationPage.clickGeneralInformation()
//     emailAddressInputPage.verifyPageTitle('Email Address')
//     emailAddressInputPage.enterEmailAddress('tasmiya.k@krazybee.com')
//     emailAddressInputPage.verifyBackLabel()
//     emailAddressInputPage.clickBackLabel()
//     profileInformationPage.verifyPagetitle('Profile Information')
//     profileInformationPage.clickGeneralInformation()
//     emailAddressInputPage.verifyPageTitle('Email Address')
//     cy.go('back')
//     profileInformationPage.verifyPagetitle('Profile Information')

// })

// it('KB-T21309 (1.0)Check the soft back and hard back buttons on Work Email Validation info screen after post loan flow ', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-SA-emplymentTab.json' })
//     cy.intercept('**/products?productId=**', { fixture: 'loan/sa/SA-EmploymentTab.json' })
//     cy.intercept('**/me?type=employment&productid=**', { fixture: 'loan/sa/SA-EmpTabEnabled.json' })
//     cy.intercept('**/me?type=employment', { fixture: 'loan/sa/SA-Emp-EmailidTab.json' })

//     cy.visit('/newhome', { failOnStatusCode: false })
//     homePage.verifyPersonalLoanSalariedLabel('PERSONAL LOAN - SALARIED')
//     homePage.clickApplyNowBtn()
//     saProductDetailsPage.verifyLoanAmountUptoLabel('Loan amount up to')
//     saProductDetailsPage.clickApplyNowBtn()
//     saEmpDetailsPage.clickEmploymentTab()
//     saVerifyEmploymentPage.verifyPageTitle('Verify Employment')
//     saVerifyEmploymentPage.verifyWorkEmailLabel('Work Email')
//     saVerifyEmploymentPage.verifyBackLabel()
//     saVerifyEmploymentPage.clickBackLabel()
//     saEmpDetailsPage.verifyPageTitle('Employment details')
//     saEmpDetailsPage.clickEmploymentTab()
//     cy.go(-1)
//     saVerifyEmploymentPage.verifyPageTitle('Verify Employment')
// })

// it('1-KB-T37393 (1.0) DISBURSAL: Check if the disbursal is happening for the MLA-5K (E-sign with Aadhar Digitap)', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-6.2kFPL.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: 'loan/fpl/fplPage-6.2k.json' })
//     cy.intercept('**/preloanre?productId=14&action=getNow&prIeLoanEvent=preLoanGetNowClick&src=cash', { fixture: 'loan/fpl/fpl6.2KPreloanREPage.json' })
//     cy.intercept('**/products?productId=**', { fixture: '/loan/fpl/viewSummayAndChargesPage.json' })
//     cy.intercept('**/products/calcfees?productid=14&loanamt=6200&tenure=**', { fixture: 'loan/fpl/fplLoanAmountDetailsPage-FeesCalculation.json' })
//     cy.intercept('**/ins/policies/details?premium_id=**', { fixture: 'insurance/premiumDetailsPage-FPL.json' })
//     cy.intercept('**/me/bank?productid=**', { fixture: 'bank/selectBankAccountPage-BankSelected.json' })
//     cy.intercept('**//loan/la?updateMFILimit=0&productid=**', { fixture: '/loan/esignWithDigitab.json' })
//     // cy.intercept('**/loan/la?updateMFILimit=**', { fixture: '/loan/esignWithAdhar.json' })
//     cy.intercept('**/loan/la?type=digitap&productid**', { fixture: 'loan/sa/sanctionLetterPage.json' })
//     cy.intercept('**/me/tnc/loanSanctionLetter', { fixture: '/loan/loanSanctionLetterEsingnAdhar.json' })
//     cy.intercept('**/me/tnc/loanSignService', { fixture: '/loan/esignDigitabSignService.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFPL4KGetNowBtn()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.verifyPageTitle('Sign Loan Document')
//     signLoanDocumentPage.verifyDigitalSignInText('Digital sign with Face IDRequires OTP + Face verification')
//     signLoanDocumentPage.verifyESignText('E-sign with Aadhaar')
//     signLoanDocumentPage.clickESignButton()
//     signLoanDocumentPage.clickContinueBtn()
//     kfsSanctionLetterPage.verifyContinueToSignLoanDocumentText('Continue to Sign Loan Document')
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     signServicePage.clickContinueButton()
//     signServiceOTPInputPage.enterOTP('395389')
// })

// it('2-KB-T37393 (1.0) DISBURSAL: Check if the disbursal is happening for the MLA-5K (E-sign with Aadhar Digitap)', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-PendingFPLLoan.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.verifyLoanActiveText(' Loan Active')
// })

// it('KB-T52698 (1.0) Ensure FPL Loan Creation is success when both PD Points and Coupon is applied', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-MLASILVER.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: 'loan/fpl/fplPage-5k.json' })
//     cy.intercept('**/preloanre?productId=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-preLoanRE-srcCash.json' })
//     cy.intercept('**/products?productId=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-productID14.json' })
//     cy.intercept('**/products/calcfees?productid=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-feescalculations.json' })
//     cy.intercept('**/products/verifycoupon?productid=**', { fixture: 'loan/repaymentSchedulePage/verifyCouponcode.json' })
//     cy.intercept('**/me/bank?couponCode=**', { fixture: 'bank/bankAccountVerificationPage-CouponCode.json' })
//     cy.intercept('**/loan/la?updateMFILimit=**', { fixture: 'loan/signLoanDocumentPage-Enable-ESignAndDigFaceID.json' })
//     cy.intercept('**/loan/la?type=**', { fixture: 'loan/fpl/sanctionPage-fund-KreditBeePVTLTD.json' })
//     cy.intercept('**/me/tnc/loanSanctionLetter', { fixture: 'loan/loanSanctionLetterPage.json' })
//     cy.intercept('**/me/otp?reason=clickwrap&kbloanId=**', { fixture: 'otp/otp-sanctionOTP.json' })

//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFPL4KGetNowBtn()
//     fplLoanAmountTenurePage.scrollSliderselectLoanAmount()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.clickApplyCouponCodeLabel()
//     applyCouponCodeOrPointsPage.enterCouponCodeInput('TEST11')
//     applyCouponCodeOrPointsPage.verifyPageTitle('Apply Coupon code or Points')
//     applyCouponCodeOrPointsPage.clickApplyBtn()
//     // fplLoanAmountDetailsPage.verifyCouponAppliedLabel('Apply Coupon code ')
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.clickDigitalSignButton()
//     signLoanDocumentPage.clickContinueBtn()
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     signDocumentPage.verifyContinueText('Continue')
//     signDocumentPage.clickContinueButton()
//     signServicePage.verifyIPAddressValue('122.185.107.110')
//     signServicePage.verifyConsentReadText('I had carefully read the Standard Terms and Conditions and the Most important Terms and Conditions for availing loan from the lender')
//     signServicePage.verifyConsentUnderstoodText(' I had understood and read the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender.')
//     signServicePage.verifyConsentLegalAndBindingText(' I had further understand that upon acceptance of the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender, a legal and binding agreement shall be created between us under the Indian Contract Act, 1872 read with Information Technology Act, 2000.')
//     signServicePage.selectConsent()
//     signServicePage.verifyContinueButtonText('Continue ')
//     signServicePage.clickContinueButton()
//     cy.clock()
//     signServiceOTPInputPage.enterOTP('123456')
//     signServiceOTPInputPage.verifyTimerValue('(00:30)')
// })

// it('1-KB-T18261 (1.0)Check whether the loan creation is happening or not through E-sign with aadhaar gateway.', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-6.2kFPL.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: 'loan/fpl/fplPage-6.2k.json' })
//     cy.intercept('**/preloanre?productId=14&action=getNow&prIeLoanEvent=preLoanGetNowClick&src=cash', { fixture: 'loan/fpl/fpl6.2KPreloanREPage.json' })
//     cy.intercept('**/products?productId=**', { fixture: '/loan/fpl/viewSummayAndChargesPage.json' })
//     cy.intercept('**/products/calcfees?productid=14&loanamt=6200&tenure=**', { fixture: 'loan/fpl/fplLoanAmountDetailsPage-FeesCalculation.json' })
//     cy.intercept('**/ins/policies/details?premium_id=**', { fixture: 'insurance/premiumDetailsPage-FPL.json' })
//     cy.intercept('**/me/bank?productid=**', { fixture: 'bank/selectBankAccountPage-BankSelected.json' })
//     cy.intercept('**//loan/la?updateMFILimit=0&productid=**', { fixture: '/loan/esignWithDigitab.json' })
//     // cy.intercept('**/loan/la?updateMFILimit=**', { fixture: '/loan/esignWithAdhar.json' })
//     cy.intercept('**/loan/la?type=digitap&productid**', { fixture: 'loan/sa/sanctionLetterPage.json' })
//     cy.intercept('**/me/tnc/loanSanctionLetter', { fixture: '/loan/loanSanctionLetterEsingnAdhar.json' })
//     cy.intercept('**/me/tnc/loanSignService', { fixture: '/loan/esignDigitabSignService.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFPL4KGetNowBtn()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.verifyPageTitle('Sign Loan Document')
//     signLoanDocumentPage.verifyDigitalSignInText('Digital sign with Face IDRequires OTP + Face verification')
//     signLoanDocumentPage.verifyESignText('E-sign with Aadhaar')
//     signLoanDocumentPage.clickESignButton()
//     signLoanDocumentPage.clickContinueBtn()
//     kfsSanctionLetterPage.verifyContinueToSignLoanDocumentText('Continue to Sign Loan Document')
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     signServicePage.clickContinueButton()
//     signServiceOTPInputPage.enterOTP('395389')
// })

// it('2-KB-T18261 (1.0)Check whether the loan creation is happening or not through E-sign with aadhaar gateway.', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-PendingFPLLoan.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.verifyLoanActiveText(' Loan Active')
// })

// it('1-KB-T11627 (1.0)Check whether the loan creation is happening or not for Paperless aadhaar users.', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-6.2kFPL.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: 'loan/fpl/fplPage-6.2k.json' })
//     cy.intercept('**/preloanre?productId=14&action=getNow&prIeLoanEvent=preLoanGetNowClick&src=cash', { fixture: 'loan/fpl/fpl6.2KPreloanREPage.json' })
//     cy.intercept('**/products?productId=**', { fixture: '/loan/fpl/viewSummayAndChargesPage.json' })
//     cy.intercept('**/products/calcfees?productid=14&loanamt=6200&tenure=**', { fixture: 'loan/fpl/fplLoanAmountDetailsPage-FeesCalculation.json' })
//     cy.intercept('**/ins/policies/details?premium_id=**', { fixture: 'insurance/premiumDetailsPage-FPL.json' })
//     cy.intercept('**/me/bank?productid=**', { fixture: 'bank/selectBankAccountPage-BankSelected.json' })
//     cy.intercept('**/loan/la?updateMFILimit=**', { fixture: 'loan/signLoanDocumentPage-Enable-ESignAndDigFaceID.json' })
//     cy.intercept('**/loan/la?type=kb&productid=**', { fixture: '/loan/sanctionLetterPaperlessAdhar.json' })
//     cy.intercept('**/me/tnc/loanSanctionLetter', { fixture: 'loan/sa/loanSanctionLetterPage.json' })
//     cy.intercept('**/me/tnc/loanSignService', { fixture: 'loan/sa/signServicePage.json' })
//     cy.intercept('**/me/otp?reason=clickwrap&kbloanId=**', { fixture: 'otp/otpPage-SignService.json' })
//     cy.intercept('**/me?source=session', { fixture: 'loan/sa/loanApplicationSubmittedPage.json' })
//     cy.intercept('**/me/otp?reason=clickwrap', { fixture: 'loan/sa/otpPage-otpsubmit.json' })
//     cy.intercept('**/me/loan', { fixture: 'loan/sa/LoanApplicationSubmittedPage-applSubmitted.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFPL4KGetNowBtn()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.verifyPageTitle('Sign Loan Document')
//     signLoanDocumentPage.verifyDigitalSignInText('Digital sign with Face IDRequires OTP + Face verification')
//     signLoanDocumentPage.verifyESignText('E-sign with Aadhaar')
//     signLoanDocumentPage.clickDigitalSignButton()
//     signLoanDocumentPage.clickContinueBtn()
//     kfsSanctionLetterPage.verifypageTitle('KFS & Sanction letter')
//     kfsSanctionLetterPage.verifyLoanSanctionedByLabel('Your loan is being sanctioned by:')
//     kfsSanctionLetterPage.verifyLenderNameText('Krazybee Services Private Limited.')
//     kfsSanctionLetterPage.verifyConsentSanctionLetterText('I have read and understood the Key Fact Statement and Sanction Letter issued by the Lender(s) in respect of my loan application and I accept the same. I also understand and agree to continue receiving promotional communication from the Lenders and in respect of the value added services being offered by KreditBee.')
//     kfsSanctionLetterPage.selectBoxSanctionLetter('Continue to Sign Loan Document')
//     kfsSanctionLetterPage.verifyContinueToSignLoanDocumentText('Continue to Sign Loan Document')
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     signDocumentPage.verifyPageTitle('Sign Document')
//     cy.get('[data-lazyload-listened="32"]').scrollTo('bottom')
//     signDocumentPage.verifyPaperlessAdharImage()
//     signDocumentPage.verifyInfoSignDocumentText('These Standard Terms & Conditions along with the Most Important Terms and Conditions form a legal and binding agreement upon acceptance pursuant to the Indian Contract Act, 1872 and the Information Technology Act, 2000.')
//     signDocumentPage.verifyContinueText('Continue')
//     signDocumentPage.clickContinueButton()
//     signServicePage.clickConsentReadText()
//     signServicePage.clickConsentUnderstoodText()
//     signServicePage.clickConsentLegalAndBindingText()
//     signServicePage.clickContinueButton()
//     signServiceOTPInputPage.enterOTP('395389')
//     loanApplicationSubmittedPage.verifypageTitle('Loan Application submitted')
// })

// it('2-KB-T11627 (1.0)Check whether the loan creation is happening or not for Paperless aadhaar users.', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-PendingFPLLoan.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.verifyLoanActiveText(' Loan Active')
// })

// it('KB-T58196 (1.0) When Agreement fee is not set or set to 0/NULL, ensure Agreement fee is not charged for chennai office', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-6.2kFPL.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: 'loan/fpl/fplPage-6.2k.json' })
//     cy.intercept('**/preloanre?productId=14&action=getNow&prIeLoanEvent=preLoanGetNowClick&src=cash', { fixture: 'loan/fpl/fpl6.2KPreloanREPage.json' })
//     cy.intercept('**/products?productId=**', { fixture: '/loan/fpl/viewSummaryPageWithNoDocFees.json' })
//     cy.intercept('**/products/calcfees?productid=14&loanamt=6200&tenure=**', { fixture: 'loan/fpl/fplLoanAmountDetailsPage-FeesCalculation.json' })
//     cy.intercept('**/ins/policies/details?premium_id=**', { fixture: 'insurance/premiumDetailsPage-FPL.json' })
//     cy.intercept('**/me/bank?productid=**', { fixture: 'bank/selectBankAccountPage-BankSelected.json' })
//     cy.intercept('**/loan/la?updateMFILimit=**', { fixture: 'loan/signLoanDocumentPage-Enable-ESignAndDigFaceID.json' })
//     cy.intercept('**/loan/la?type=kb&productid=**', { fixture: '/loan/sanctionLetterPaperlessAdhar.json' })
//     cy.intercept('**/me/tnc/loanSanctionLetter', { fixture: 'loan/sa/loanSanctionLetterPage.json' })
//     cy.intercept('**/me/tnc/loanSignService', { fixture: 'loan/sa/signServicePage.json' })
//     cy.intercept('**/me/otp?reason=clickwrap&kbloanId=**', { fixture: 'otp/otpPage-SignService.json' })
//     cy.intercept('**/me?source=session', { fixture: 'loan/sa/loanApplicationSubmittedPage.json' })
//     cy.intercept('**/me/otp?reason=clickwrap', { fixture: 'loan/sa/otpPage-otpsubmit.json' })
//     cy.intercept('**/me/loan', { fixture: 'loan/sa/LoanApplicationSubmittedPage-applSubmitted.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFPL4KGetNowBtn()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.verifyLoanDocumantSigningFeeDisabled()
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.verifyPageTitle('Sign Loan Document')
//     signLoanDocumentPage.verifyDigitalSignInText('Digital sign with Face IDRequires OTP + Face verification')
//     signLoanDocumentPage.verifyESignText('E-sign with Aadhaar')
//     signLoanDocumentPage.clickDigitalSignButton()
//     signLoanDocumentPage.clickContinueBtn()
//     kfsSanctionLetterPage.verifypageTitle('KFS & Sanction letter')
//     kfsSanctionLetterPage.verifyLoanSanctionedByLabel('Your loan is being sanctioned by:')
//     kfsSanctionLetterPage.verifyLenderNameText('Krazybee Services Private Limited.')
//     kfsSanctionLetterPage.verifyConsentSanctionLetterText('I have read and understood the Key Fact Statement and Sanction Letter issued by the Lender(s) in respect of my loan application and I accept the same. I also understand and agree to continue receiving promotional communication from the Lenders and in respect of the value added services being offered by KreditBee.')
//     kfsSanctionLetterPage.selectBoxSanctionLetter('Continue to Sign Loan Document')
//     kfsSanctionLetterPage.verifyContinueToSignLoanDocumentText('Continue to Sign Loan Document')
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     signDocumentPage.verifyPageTitle('Sign Document')
//     cy.get('[data-lazyload-listened="32"]').scrollTo('bottom')
//     signDocumentPage.verifyPaperlessAdharImage()
//     signDocumentPage.verifyInfoSignDocumentText('These Standard Terms & Conditions along with the Most Important Terms and Conditions form a legal and binding agreement upon acceptance pursuant to the Indian Contract Act, 1872 and the Information Technology Act, 2000.')
//     signDocumentPage.verifyContinueText('Continue')
//     signDocumentPage.clickContinueButton()
//     signServicePage.clickConsentReadText()
//     signServicePage.clickConsentUnderstoodText()
//     signServicePage.clickConsentLegalAndBindingText()
//     signServicePage.clickContinueButton()
//     signServiceOTPInputPage.enterOTP('395389')
//     loanApplicationSubmittedPage.verifypageTitle('Loan Application submitted')
// })

// it('KB-T60806 (1.0) [CSR] Verify Confirm User is able to apply the Partial Points during the CSR Report Generation', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-8k.json' })
//     cy.intercept('**/myaccount', { fixture: 'accounts/accountsPage.json' })
//     cy.intercept('**/creditreport', { fixture: '/creditScoreReport/CSRPayAndGetOTP.json' })
//     cy.intercept('**/otp?reason=creditreport', { fixture: 'creditScoreReport/CSROtpPointsInputPage.json' })
//     cy.intercept('**/payment?v=**', { fixture: '/creditScoreReport/CSRPaymentOption-Debitcard.json' })

//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickcreditScoreIcon()
//     csrInfoPage.clickPayAndGetReportButton()
//     csrOTPInputPage.enterOTP('123456')
//     csrOTPInputPage.checkConsentBox()
//     csrOTPInputPage.clickSubmitBtn()
//     csrPaymentOptionsPage.verifyPayNowLabel('Pay Now')
//     csrPaymentOptionsPage.verifyCouponOrpointsButton('Pay with Coupon Code or Points')
//     csrPaymentOptionsPage.verifyPayWithNextLoanLabel('Pay with Next Loan')
//     csrPaymentOptionsPage.clickCouponOrpointsButton()
//     applyCouponCodeOrPointsPage.clickApplyPoints30()
//     csrPaymentOptionsPage.verifyCouponSuccessFullMeassage('applied successfully !')
//     csrPaymentOptionsPage.clickPayNowButton()
//     paymentOptionPage.verifyPayWithDebitCardText('Pay with Debit Card')
//     paymentOptionPage.verifyNetBankingText('NetBanking')
//     paymentOptionPage.clickPayWithDebitCard()

// })

// it('KB-T56042 (1.0) When proc_fee_flag = 1, ensure Processing fee is charged for both Partner and KB for non KB fund and KB Points is applied along with default PD points and CSR + Insurance opted', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-MLASILVER.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: 'loan/fpl/fplPage-5k.json' })
//     cy.intercept('**/preloanre?productId=14&action=getNow&preLoanEvent=preLoanGetNowClick&src=cash', { fixture: 'loan/fpl/fplLoanAmountTenurePage-preLoanRE-srcCash.json' })
//     cy.intercept('**/products?productId=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-productID14.json' })
//     cy.intercept('**/products/calcfees?productid=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-feescalculations.json' })
//     cy.intercept('**/me/bank?productid=**', { fixture: 'bank/bankAccountVerifiedPage.json' })
//     cy.intercept('**/loan/la?updateMFILimit=**', { fixture: 'loan/signLoanDocumentPage-Enable-ESignAndDigFaceID.json' })
//     cy.intercept('**/loan/la?type=**', { fixture: 'loan/fpl/sanctionPage-fund-WC.json' })
//     cy.intercept('**/me/otp?reason=clickwrap&kbloanId=**', { fixture: 'otp/otp-sanctionOTP.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFPL4KGetNowBtn()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.verifyBuyEMIText('Buy EMI Protect : ₹ 73')
//     fplLoanAmountDetailsPage.verifyApplyCouponCodeLabel_1('Apply Coupon code or Points')
//     fplLoanAmountDetailsPage.clickApplyCouponCodeLabel()
//     applyCouponCodeOrPointsPage.clickApplyPointsButton()
//     fplLoanAmountDetailsPage.verifyCouponCodeSuccessfullLoanText('points applied successfully !')
//     fplLoanAmountDetailsPage.verifyCSRFeeLabel('Credit Score Report Fee')
//     fplLoanAmountDetailsPage.verifyInsurancePremiumLabel('Insurance Premium ')
//     fplLoanAmountDetailsPage.verifyRepaymentShedulePageButton()
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.verifyPrincipalLabel('Principal')
//     repaymentSchedulePage.verifyInterestLabel('Interest')
//     repaymentSchedulePage.verifyDueDateLabel('Due Date')
//     repaymentSchedulePage.verifyRepayableAmountLabel('Repayable Amount')
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.clickDigitalSignButton()
//     signLoanDocumentPage.clickContinueBtn()
//     //kfs sanction letter - validation
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     //sanction letter -validation

//     signDocumentPage.clickContinueButton()
//     //signServicePage - validation
//     signServicePage.verifyConsentReadText('I had carefully read the Standard Terms and Conditions and the Most important Terms and Conditions for availing loan from the lender')
//     signServicePage.verifyConsentUnderstoodText(' I had understood and read the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender.')
//     signServicePage.verifyConsentLegalAndBindingText(' I had further understand that upon acceptance of the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender, a legal and binding agreement shall be created between us under the Indian Contract Act, 1872 read with Information Technology Act, 2000.')
//     signServicePage.selectConsent()
//     signServicePage.verifyContinueButtonText('Continue ')
//     signServicePage.clickContinueButton()
//     // //OTP service validation
//     cy.clock()
//     signServiceOTPInputPage.enterOTP('123456')
//     // cy.tick(4000)
//     //signServiceOTPInputPage.verifyTimerValue('(00:26)')
// })
// it('KB-T56056 (1.0)When proc_fee_flag = 2, ensure entire Processing fee is charged by Partner for non KB fund and KB Points is applied along with default PD points and CSR opted', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-MLASILVER.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: 'loan/fpl/fplPage-5k.json' })
//     cy.intercept('**/preloanre?productId=14&action=getNow&preLoanEvent=preLoanGetNowClick&src=cash', { fixture: 'loan/fpl/fplLoanAmountTenurePage-preLoanRE-srcCash.json' })
//     cy.intercept('**/products?productId=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-productID14.json' })
//     cy.intercept('**/products/calcfees?productid=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-feescalculations.json' })
//     cy.intercept('**/me/bank?productid=**', { fixture: 'bank/bankAccountVerifiedPage.json' })
//     cy.intercept('**/loan/la?updateMFILimit=**', { fixture: 'loan/signLoanDocumentPage-Enable-ESignAndDigFaceID.json' })
//     cy.intercept('**/loan/la?type=**', { fixture: 'loan/fpl/sanctionPage-fund-WC.json' })
//     cy.intercept('**/me/otp?reason=clickwrap&kbloanId=**', { fixture: 'otp/otp-sanctionOTP.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFPL4KGetNowBtn()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.verifyBuyEMIText('Buy EMI Protect : ₹ 73')
//     fplLoanAmountDetailsPage.verifyApplyCouponCodeLabel_1('Apply Coupon code or Points')
//     fplLoanAmountDetailsPage.clickApplyCouponCodeLabel()
//     applyCouponCodeOrPointsPage.clickApplyPointsButton()
//     fplLoanAmountDetailsPage.verifyCouponCodeSuccessfullLoanText('points applied successfully !')
//     fplLoanAmountDetailsPage.verifyCSRFeeLabel('Credit Score Report Fee')
//     fplLoanAmountDetailsPage.verifyInsurancePremiumLabel('Insurance Premium ')
//     fplLoanAmountDetailsPage.verifyRepaymentShedulePageButton()
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.clickDigitalSignButton()
//     signLoanDocumentPage.clickContinueBtn()
//     //kfs sanction letter - validation
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     //sanction letter -validation

//     signDocumentPage.clickContinueButton()
//     //signServicePage - validation
//     signServicePage.verifyConsentReadText('I had carefully read the Standard Terms and Conditions and the Most important Terms and Conditions for availing loan from the lender')
//     signServicePage.verifyConsentUnderstoodText(' I had understood and read the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender.')
//     signServicePage.verifyConsentLegalAndBindingText(' I had further understand that upon acceptance of the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender, a legal and binding agreement shall be created between us under the Indian Contract Act, 1872 read with Information Technology Act, 2000.')
//     signServicePage.selectConsent()
//     signServicePage.verifyContinueButtonText('Continue ')
//     signServicePage.clickContinueButton()
//     // //OTP service validation
//     cy.clock()
//     signServiceOTPInputPage.enterOTP('123456')
//     cy.tick(4000)
//     signServiceOTPInputPage.verifyTimerValue('(00:26)')
// })

// it('KB-T56028 (1.0)When proc_fee_flag = 0, ensure entire Processing fee is charged by KB for non KB fund and KB Points is applied along with default PD points and CSR + Insurance opted', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-MLASILVER.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: 'loan/fpl/fplPage-5k.json' })
//     cy.intercept('**//ecom/offers?type=preloanBanner', { fixture: '/loan/fpl/fplOffres6k.json' })
//     cy.intercept('**/preloanre?productId=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-preLoanRE-srcCash.json' })
//     cy.intercept('**/products?productId=**', { fixture: 'loan/fpl/fpllLoanAmountTernurepage-product.json' })
//     cy.intercept('**/products/calcfees?productid=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-feescalculations.json' })
//     cy.intercept('**/me/bank?productid=**', { fixture: 'bank/bankAccountVerifiedPage.json' })
//     cy.intercept('**/loan/la?updateMFILimit=**', { fixture: 'loan/signLoanDocumentPage-Enable-ESignAndDigFaceID.json' })
//     cy.intercept('**/loan/la?type=**', { fixture: 'loan/fpl/sanctionPage-fund-WC.json' })
//     cy.intercept('**/me/otp?reason=clickwrap&kbloanId=**', { fixture: 'otp/otp-sanctionOTP.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFPL4KGetNowBtn()
//     fplLoanAmountTenurePage.clickSelectLoanAmountMinValue()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.verifyBuyEMIText('Buy EMI Protect : ₹ 73')
//     fplLoanAmountDetailsPage.verifyApplyCouponCodeLabel_1('Apply Coupon code or Points')
//     fplLoanAmountDetailsPage.clickApplyCouponCodeLabel()
//     applyCouponCodeOrPointsPage.clickApplyPointsButton()
//     fplLoanAmountDetailsPage.verifyCouponCodeSuccessfullLoanText('points applied successfully !')
//     fplLoanAmountDetailsPage.clickGetMyCSRCheckBox()
//     fplLoanAmountDetailsPage.verifyCSRFeeLabel('Credit Score Report Fee')
//     fplLoanAmountDetailsPage.verifyInsurancePremiumLabel('Insurance Premium ')
//     fplLoanAmountDetailsPage.verifyRepaymentShedulePageButton()
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.clickDigitalSignButton()
//     signLoanDocumentPage.clickContinueBtn()
//     //kfs sanction letter - validation
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     //sanction letter -validation
//     signDocumentPage.clickContinueButton()
//     //signServicePage - validation
//     signServicePage.verifyConsentReadText('I had carefully read the Standard Terms and Conditions and the Most important Terms and Conditions for availing loan from the lender')
//     signServicePage.verifyConsentUnderstoodText(' I had understood and read the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender.')
//     signServicePage.verifyConsentLegalAndBindingText(' I had further understand that upon acceptance of the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender, a legal and binding agreement shall be created between us under the Indian Contract Act, 1872 read with Information Technology Act, 2000.')
//     signServicePage.selectConsent()
//     signServicePage.verifyContinueButtonText('Continue ')
//     signServicePage.clickContinueButton()
//     // //OTP service validation
//     cy.clock()
//     signServiceOTPInputPage.enterOTP('123456')
//     cy.tick(4000)
//     signServiceOTPInputPage.verifyTimerValue('(00:26)')
// })

// it('KB-T56030 (1.0)When proc_fee_flag = 1, ensure Processing fee is charged for both partner and KB based on colendingpercentage for non KB fund', () => {
//     cy.intercept('**/home', { fixture: 'home/homepage-MLAX.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: 'loan/fpl/Amount3k-Tenure3-MLASILVER-subBandBad.json' })
//     cy.intercept('**/products?productId=**', { fixture: '/loan/fpl/viewSummayAndChargesPage.json' })
//     cy.intercept('**/products/calcfees?productid=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-feescalculations.json' })
//     cy.intercept('**/me/bank?productid=**', { fixture: 'bank/bankAccountVerifiedPage.json' })
//     cy.intercept('**/loan/la?updateMFILimit=**', { fixture: 'loan/signLoanDocumentPage-Enable-ESignAndDigFaceID.json' })
//     cy.intercept('**/loan/la?type=**', { fixture: 'loan/fpl/sanctionPage-fund-INCRED.json' })
//     cy.intercept('**/me/otp?reason=clickwrap&kbloanId=**', { fixture: 'otp/otp-sanctionOTP.json' })
//     cy.intercept('**/me/otp?reason=clickwrap', { fixture: 'otp/otpSignServicePage.json' })
//     cy.intercept('**/me/loan', { fixture: 'otp/loanApplicationPage-Submitted.json' })
//     cy.intercept('**/me?source=session', { fixture: 'otp/loanApplicationPage-InsSubmit.json' })
//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFPL4KGetNowBtn()
//     cy.wait(2000)
//     fplLoanAmountTenurePage.scrollSliderselectLoanAmount()
//     fplLoanAmountTenurePage.scrollSliderselectLoanAmountLeft()
//     fplLoanAmountTenurePage.verifySelectLoanAmountMinValue3000()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.verifyProcessingFeeText('₹ 175')
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.clickDigitalSignButton()
//     signLoanDocumentPage.clickContinueBtn()
//     //kfs sanction letter - validation
//     kfsSanctionLetterPage.verifyPageTitle('Sanction letter')
//     kfsSanctionLetterPage.verifyLoanSanctionedByLabel('Your loan is being sanctioned by:')
//     kfsSanctionLetterPage.verifyLenderNameText('Visu Leasing and Finance Private Limited.')
//     kfsSanctionLetterPage.verifyContinueToSignLoanDocumentText('Continue to Sign Loan Document')
//    // kfsSanctionLetterPage.verifysanctionLetterdocument()
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     //sanction letter -validation
//     signDocumentPage.verifyPageTitle('Sign Document')
//     signDocumentPage.verifyInfoSignDocumentText('These Standard Terms & Conditions along with the Most Important Terms and Conditions form a legal and binding agreement upon acceptance pursuant to the Indian Contract Act, 1872 and the Information Technology Act, 2000.')
//     signDocumentPage.verifyContinueText('Continue')
//     signDocumentPage.clickContinueButton()
//     signServicePage.verifyConsentReadText('I had carefully read the Standard Terms and Conditions and the Most important Terms and Conditions for availing loan from the lender')
//     signServicePage.verifyConsentUnderstoodText(' I had understood and read the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender.')
//     signServicePage.verifyConsentLegalAndBindingText(' I had further understand that upon acceptance of the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender, a legal and binding agreement shall be created between us under the Indian Contract Act, 1872 read with Information Technology Act, 2000.')
//     signServicePage.selectConsent()
//     signServicePage.verifyContinueButtonText('Continue ')
//     signServicePage.clickContinueButton()
//     // //OTP service validation
//     signServiceOTPInputPage.enterOTP('123456')
//     loanApplicationSubmittedPage.verifypageTitle('Loan Application submitted')
// })

// it('KB-T60167 (1.0)Verify Confirmed user is able to Generate the CSR Report with NetBanking (NB) mode', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-8k.json' })
//     cy.intercept('**/myaccount', { fixture: 'accounts/accountsPage.json' })
//     cy.intercept('**/creditreport', { fixture: '/creditScoreReport/CSRPayAndGetOTP.json' })
//     cy.intercept('**/otp?reason=creditreport', { fixture: 'creditScoreReport/CSROtpPointsInputPage.json' })
//     cy.intercept('**/payment?v=**', { fixture: '/creditScoreReport/CSRPaymentOption-Debitcard.json' })

//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickcreditScoreIcon()
//     csrInfoPage.clickPayAndGetReportButton()
//     csrOTPInputPage.enterOTP('123456')
//     csrOTPInputPage.checkConsentBox()
//     csrOTPInputPage.clickSubmitBtn()
//     csrPaymentOptionsPage.verifyPayNowLabel('Pay Now')
//     csrPaymentOptionsPage.verifyCouponOrpointsButton('Pay with Coupon Code or Points')
//     csrPaymentOptionsPage.verifyPayWithNextLoanLabel('Pay with Next Loan')
//     csrPaymentOptionsPage.clickCouponOrpointsButton()
//     applyCouponCodeOrPointsPage.clickApplyPoints30()
//     csrPaymentOptionsPage.verifyCouponSuccessFullMeassage('applied successfully !')
//     csrPaymentOptionsPage.clickPayNowButton()
//     paymentOptionPage.verifyPayWithDebitCardText('Pay with Debit Card')
//     paymentOptionPage.verifyNetBankingText('NetBanking')
//     paymentOptionPage.clickNetBankingBlock()
//     paymentOptionPage.clickSBIBankText()
// })

// it('KB-T52701 (1.0)Ensure SA Loan Creation is success when ProcessingFee becomes zero after applying coupon code', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-SA-NoProccessingFee.json' })
//     cy.intercept('**/preloanre?productId=**', { fixture: 'loan/sa/SA-Amount30k-TenurePage.json' })
//     cy.intercept('**/ecom/offers?type=preloanBanner', { fixture: '/loan/sa/SA-PreloanBaner-Offers.json' })
//     cy.intercept('**/products?productId=**', { fixture: 'loan/sa/viewRepaymentSchedulePage-SA30k.json' })
//     cy.intercept('**/products/calcfees?productid=**', { fixture: 'loan/sa/SA-LoanAmountTenurePage-feescalculationsProcessingFeesZero.json' })
//     cy.intercept('**/products/verifycoupon?productid=**', { fixture: '/loan/repaymentSchedulePage/RepaymentSchedule30k-Couponcode.json' })
//     cy.intercept('**/me/bank?couponCode=**', { fixture: 'bank/bankAccountVerificationPageProcessingFeesZero-CouponCode.json' })
//     cy.intercept('**/loan/la?updateMFILimit=**', { fixture: 'loan/signLoanDocumentPage-Enable-ESignAndDigFaceID.json' })
//     cy.intercept('**/loan/la?type=**', { fixture: 'loan/fpl/sanctionPage-fund-KreditBeePVTLTD.json' })
//     cy.intercept('**/me/tnc/loanSanctionLetter', { fixture: 'loan/loanSanctionLetterPage.json' })
//     cy.intercept('**/me/otp?reason=clickwrap&kbloanId=**', { fixture: 'otp/otp-sanctionOTP.json' })

//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock1Btn()
//     cy.wait(3000)
//     saLoanAmountTenurePage.verifySelectLoanAmountLabel()
//     saLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     // fplLoanAmountDetailsPage.verifyProcessingFee()
//     fplLoanAmountDetailsPage.verifyProcessingFeeText('₹ 1,315')
//     fplLoanAmountDetailsPage.verifyApplyCouponCodeLabel()
//     saLoanAmountDetailsPage.clickGetMyCSRCheckBox()
//     saLoanAmountDetailsPage.verifyApplyCouponCodeLabel()
//     applyCouponCodeOrPointsPage.enterCouponCodeInput('TEST11')
//     applyCouponCodeOrPointsPage.clickApplyBtn()
//     fplLoanAmountDetailsPage.verifyProcessingFee()
//     fplLoanAmountDetailsPage.verifyProcessingFeeText('₹ 0')
//     saLoanAmountDetailsPage.clickGetMyCSRCheckBox()
//     fplLoanAmountDetailsPage.verifyBuyEMIcheckBox()
//     fplLoanAmountDetailsPage.verifyGSTlbl('GST @ 18%')
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.clickDigitalSignButton('Digital sign with Face ID')
//     signLoanDocumentPage.clickContinueBtn()
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     signDocumentPage.verifyInfoSignDocumentText('These Standard Terms & Conditions along with the Most Important Terms and Conditions form a legal and binding agreement upon acceptance pursuant to the Indian Contract Act, 1872 and the Information Technology Act, 2000.')
//     signDocumentPage.clickContinueButton()
//     signServicePage.verifyConsentReadText('I had carefully read the Standard Terms and Conditions and the Most important Terms and Conditions for availing loan from the lender')
//     signServicePage.verifyConsentUnderstoodText(' I had understood and read the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender.')
//     signServicePage.verifyConsentLegalAndBindingText(' I had further understand that upon acceptance of the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender, a legal and binding agreement shall be created between us under the Indian Contract Act, 1872 read with Information Technology Act, 2000.')
//     signServicePage.selectConsent()
//     signServicePage.clickContinueButton()
//     cy.clock()
//     signServiceOTPInputPage.enterOTP('123456')
//     cy.tick(4000)
//     signServiceOTPInputPage.verifyTimerValue('(00:26)')
// })

// it('KB-T52700 (1.0)Ensure FPL Loan Creation is success when ProcessingFee becomes zero after applying coupon code', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-30K-NoProcessingFee.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: '/loan/fpl/AmountMLA30K-Tenure.json' })
//     cy.intercept('**/preloanre?productId=10&action=getNow&preLoanEvent=**', { fixture: '/loan/fpl/fplLoanAmountTenurePage-preLoanRE-srcCash30K.json' })
//     cy.intercept('**/ecom/offers?type=preloanBanner', { fixture: '/loan/fpl/FplMLA30K-PreloanBaner-Offers.json' })
//     cy.intercept('**/products?productId=**', { fixture: '/loan/fpl/fplLoanAmount-MLA30K-TenurePage.json' })
//     cy.intercept('**/products/calcfees?productid=**', { fixture: '/loan/fpl/fplLoanAmount-MLA30K-TenurePage-feesCalculations.json' })
//     cy.intercept('**/products/verifycoupon?productid=**', { fixture: '/loan/repaymentSchedulePage/RepaymentSchedule30k-Couponcode.json' })
//     cy.intercept('**/me/bank?couponCode=**', { fixture: 'bank/bankAccountVerificationPageProcessingFeesZero-CouponCode.json' })
//     cy.intercept('**/loan/la?updateMFILimit=**', { fixture: 'loan/signLoanDocumentPage-Enable-ESignAndDigFaceID.json' })
//     cy.intercept('**/loan/la?type=**', { fixture: 'loan/fpl/sanctionPage-fund-MLA10K-KreditBeePVTLTD.json' })
//     cy.intercept('**/me/tnc/loanSanctionLetter', { fixture: 'loan/loanSanctionLetterPage-MLA10K.json' })
//     cy.intercept('**/me/otp?reason=clickwrap&kbloanId=**', { fixture: 'otp/otpPage-SignService.json' })

//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFplGetNowCard1Button()
//     fplLoanAmountTenurePage.verifySelectLoanAmountLabel()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.verifyProcessingFee()
//     fplLoanAmountDetailsPage.verifyProcessingFeeText('₹ 1,903')
//     fplLoanAmountDetailsPage.verifyApplyCouponCodeLabel()
//     fplLoanAmountDetailsPage.clickApplyCouponCodeLabel()
//     applyCouponCodeOrPointsPage.enterCouponCodeInput('TEST11')
//     applyCouponCodeOrPointsPage.clickApplyBtn()
//     fplLoanAmountDetailsPage.verifyProcessingFee()
//     fplLoanAmountDetailsPage.verifyProcessingFeeText('₹ 0')
//     fplLoanAmountDetailsPage.verifyInsurancePremiumLabel()
//     fplLoanAmountDetailsPage.verifyBuyEMIcheckBox()
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.clickDigitalSignButton('Digital sign with Face ID')
//     signLoanDocumentPage.clickContinueBtn()
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     signDocumentPage.clickContinueButton()
//     signServicePage.verifyConsentReadText('I had carefully read the Standard Terms and Conditions and the Most important Terms and Conditions for availing loan from the lender')
//     signServicePage.verifyConsentUnderstoodText(' I had understood and read the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender.')
//     signServicePage.verifyConsentLegalAndBindingText(' I had further understand that upon acceptance of the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender, a legal and binding agreement shall be created between us under the Indian Contract Act, 1872 read with Information Technology Act, 2000.')
//     signServicePage.selectConsent()
//     signServicePage.verifyContinueButtonText('Continue ')
//     signServicePage.clickContinueButton()
//     cy.clock()
//     signServiceOTPInputPage.enterOTP('123456')
//     cy.tick(4000)
//     signServiceOTPInputPage.verifyTimerValue('(00:26)')

// })

// it('KB-T52706 (1.0)Ensure FPL Loan Creation is success when both PD Points and Coupon is applied and CSR with insurance is opted', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-MLA10K.json' })
//     cy.intercept('**/category?name=fplfalse', { fixture: '/loan/fpl/AmountMLA10K-Tenure.json' })
//     cy.intercept('**/preloanre?productId=**', { fixture: 'loan/fpl/fplLoanAmountTenurePage-preLoanRE-srcCash.json' })
//     cy.intercept('**/ecom/offers?type=preloanBanner', { fixture: '/loan/fpl/FplMLA10K-PreloanBaner-Offers.json' })
//     cy.intercept('**/products?productId=**', { fixture: '/loan/fpl/fplLoanAmount-MLA10K-TenurePage.json' })
//     cy.intercept('**/products/calcfees?productid=**', { fixture: '/loan/fpl/fplLoanAmount-MLA10K-TenurePage-feesCalculations.json' })
//     cy.intercept('**/products/verifycoupon?productid=**', { fixture: '/loan/repaymentSchedulePage/RepaymentSchedule-Couponcode.json' })
//     cy.intercept('**/me/bank?couponCode=**', { fixture: 'bank/bankAccountVerificationPage-CouponCode.json' })
//     cy.intercept('**/loan/la?updateMFILimit=**', { fixture: 'loan/signLoanDocumentPage-Enable-ESignAndDigFaceID.json' })
//     cy.intercept('**/loan/la?type=**', { fixture: 'loan/fpl/sanctionPage-fund-MLA10K-KreditBeePVTLTD.json' })
//     cy.intercept('**/me/tnc/loanSanctionLetter', { fixture: 'loan/loanSanctionLetterPage-MLA10K.json' })
//     cy.intercept('**/me/otp?reason=clickwrap&kbloanId=**', { fixture: 'otp/otpPage-SignService.json' })
//     cy.intercept('**/me?source=session', { fixture: 'loan/sa/loanApplicationSubmittedPage.json' })
//     cy.intercept('**/me/otp?reason=clickwrap', { fixture: 'loan/sa/otpPage-otpsubmit.json' })
//     cy.intercept('**/me/loan', { fixture: 'loan/sa/LoanApplicationSubmittedPage-applSubmitted.json' })


//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickBlock2Btn()
//     fplPage.clickFplGetNowCard1Button()
//     fplLoanAmountTenurePage.verifySelectLoanAmountLabel()
//     fplLoanAmountTenurePage.clickViewSummaryAndChargesBtn()
//     fplLoanAmountDetailsPage.verifyProcessingFee()
//     fplLoanAmountDetailsPage.verifyProcessingFeeText('₹ 1,250')
//     fplLoanAmountDetailsPage.verifyApplyCouponCodeLabel()
//     fplLoanAmountDetailsPage.clickApplyCouponCodeLabel()
//     applyCouponCodeOrPointsPage.enterCouponCodeInput('PRO123')
//     applyCouponCodeOrPointsPage.clickApplyBtn()
//     fplLoanAmountDetailsPage.verifyCouponAppliedLabel('applied successfully !')
//     fplLoanAmountDetailsPage.verifyProcessingFee()
//     fplLoanAmountDetailsPage.verifyProcessingFeeText('₹ 470')
//     fplLoanAmountDetailsPage.verifyInsurancePremiumLabel()
//     fplLoanAmountDetailsPage.verifyBuyEMIcheckBox()
//     fplLoanAmountDetailsPage.clickViewRepaymentScheduleBtn()
//     repaymentSchedulePage.clickContinueBtn()
//     loanPurposePage.selectLoanPurpose('Medical expenses')
//     loanPurposePage.clickContinueBtn()
//     selectBankAccountPage.clickContinueBtn()
//     signLoanDocumentPage.clickDigitalSignButton('Digital sign with Face ID')
//     signLoanDocumentPage.clickContinueBtn()
//     kfsSanctionLetterPage.clickContinueToSignLoanDocumentButton()
//     signDocumentPage.clickContinueButton()
//     signServicePage.verifyConsentReadText('I had carefully read the Standard Terms and Conditions and the Most important Terms and Conditions for availing loan from the lender')
//     signServicePage.verifyConsentUnderstoodText(' I had understood and read the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender.')
//     signServicePage.verifyConsentLegalAndBindingText(' I had further understand that upon acceptance of the Standard Terms and Conditions and the Most Important Terms and Conditions for availing loan from the Lender, a legal and binding agreement shall be created between us under the Indian Contract Act, 1872 read with Information Technology Act, 2000.')
//     signServicePage.selectConsent()
//     signServicePage.verifyContinueButtonText('Continue ')
//     signServicePage.clickContinueButton()
//     cy.clock()
//     signServiceOTPInputPage.enterOTP('123456')
//     //  loanApplicationSubmittedPage.verifyPageTitle('Loan Application submitted')
// })

// it('KB-T60168 (1.0) Ensure for Rejected customer is able to generate the CSR Report with Net Banking (NB) mode', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-CSRReject.json' })
//     cy.intercept('**/me/creditreport', { fixture: '/creditScoreReport/CSRCreditReportDetails.json' })
//     cy.intercept('**/misc/pincode?pincode=**', { fixture: '/creditScoreReport/CSRProfileInformation.json' })
//     cy.intercept('**/creditreport/details', { fixture: '/creditScoreReport/CSROTPDetails.json' })
//     cy.intercept('**/otp?reason=creditreport', { fixture: '/creditScoreReport/CSROTPInput.json' })
//     cy.intercept('**/me/otp?reason=**', { fixture: 'creditScoreReport/CSRPaymentOptionsPage.json' })
//     cy.intercept('**/payment?v=**', { fixture: '/creditScoreReport/CSRPaymentOption-Debitcard.json' })

//    cy.visit('/newhome', { failOnStatusCode: false });
//     homePage.clickcreditScoreIcon()
//     csrInfoPage.clickPayAndGetReportButton()
//     csrProfileInformationPage.enterPan('FMHPM0640A')
//     csrProfileInformationPage.enterDate('7')
//     csrProfileInformationPage.enterMonth('Aug')
//     csrProfileInformationPage.enterYear('1998')
//     csrProfileInformationPage.enterFNameinput('mastan')
//     csrProfileInformationPage.enterLastName('komodheen')
//     csrProfileInformationPage.enterEmail('komodheen.mastan@krazybee.com')
//     csrProfileInformationPage.clickAddressLine2Input('Madanapalli')
//     csrProfileInformationPage.submitButton()
//     csrOTPInputPage.enterOTP('123456')
//     csrOTPInputPage.checkConsentBox()
//     csrOTPInputPage.clickSubmitBtn()
//     csrPaymentOptionsPage.clickPayNowButton()
//     paymentOptionPage.verifyPayWithDebitCardText('Pay with Debit Card')
//     paymentOptionPage.verifyNetBankingText('NetBanking')
//     paymentOptionPage.clickNetBankingBlock()
//     paymentOptionPage.clickSBIBankText()
// })

// it('KB-T37804 (1.0)Complete the work email flow in employment details of SA', () => {
//     cy.intercept('**/home', { fixture: 'home/homePage-SA-emplymentTab.json' })
//     cy.intercept('**/products?productId=**', { fixture: 'loan/sa/SA-EmploymentTab.json' })
//     cy.intercept('**/me?type=employment&productid=**', { fixture: 'loan/sa/SA-EmpTabEnabled.json' })
//     cy.intercept('**/me?type=employment', { fixture: 'loan/sa/SA-Emp-EmailidTab.json' })
//     cy.intercept('**/me/extradetails/sa/workemailverification/otp', { fixture: '/loan/sa/SAEmpDetailsPage/EmployeeDetaile-OtpValidation.json' })
//     cy.intercept('**/me/extradetails/sa/workemailverification/otp?email=**', { fixture: '/loan/sa/SAEmpDetailsPage/EmployeeDetails-EmailValidation.json' })
//     cy.intercept('**/me/profile/doc', { fixture: '/loan/sa/SAEmpDetailsPage/EmloyeementDocumentSuccess.json' })
//     cy.visit('/newhome', { failOnStatusCode: false })
//     homePage.verifyPersonalLoanSalariedLabel('PERSONAL LOAN - SALARIED')
//     homePage.clickApplyNowBtn()
//     saProductDetailsPage.verifyLoanAmountUptoLabel('Loan amount up to')
//     saProductDetailsPage.clickApplyNowBtn()
//     saEmpDetailsPage.clickEmploymentTab()
//     saVerifyEmploymentPage.verifyPageTitle('Verify Employment')
//     saVerifyEmploymentPage.clickBackLabel()
//     saEmpDetailsPage.clickEmploymentTab()
//     cy.go(-1)
//     saEmpDetailsPage.clickEmploymentTab()
//     saVerifyEmploymentPage.verifyWorkEmailLabel('Work Email')
//     saVerifyEmploymentPage.clickVerifyEmailButton()
//     verifyWorkEmailInfoPage.verifyBackLabel()
//     verifyWorkEmailInfoPage.clickBackLabel()
//     saVerifyEmploymentPage.clickVerifyEmailButton()
//     cy.go(-1)
//     saVerifyEmploymentPage.clickVerifyEmailButton()
//     verifyWorkEmailInfoPage.verifyPageTitle(' Verify Work Email ')
//     verifyWorkEmailInfoPage.clickContinueButton()
//     verifyWorkEmailPage.enterWorkEmail('komodheen.mastan@krazybee.com')
//     verifyWorkEmailPage.clickSendOTP()
//     verifyWorkEmailOTPInputPage.enterOTP('123456')
//     verifyWorkEmailOTPInputPage.clickSubmitButton()
//     cy.intercept('**/me?type=employment', { fixture: '/loan/sa/SAEmpDetailsPage/EmployeeEmailsucess.json' })
//     saVerifyEmploymentPage.verfiyEmailVerified('Email Verified')
//     saVerifyEmploymentPage.verfiyConfirmAndContinueButton('Confirm and Continue')
//     saVerifyEmploymentPage.clickConfirmAndContinueButton()
//     cy.intercept('**/me?type=**', { fixture: '/loan/sa/SAEmpDetailsPage/SAEmployeementProductVerifyingPage.json' })
//     saVerifyWorkEmailRefreshPage.verifyPageTitle('Verifying your employment details')
//     saVerifyWorkEmailRefreshPage.verifySubTextOfVerifyingDetails('Please wait while we verify your employment details. This may take a couple of minutes.')
//     saVerifyWorkEmailRefreshPage.verifyRefreshButton('Refresh')

// })
// })